# Generated by Django 4.2.2 on 2023-12-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default=None, max_length=20, verbose_name='Ім`я')),
                ('patronymic', models.CharField(default=None, max_length=20, verbose_name='По батькові')),
                ('last_name', models.CharField(default=None, max_length=20, verbose_name='Прізвище')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логін')),
                ('password', models.CharField(default=None, max_length=255, verbose_name='Пароль')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Працівник'), ('ENGINEER', 'Інженер'), ('MANAGER', 'Менеджер'), ('COUNTER', 'Бухгалтер'), ('DIRECTOR', 'Директор')], default=('EMPLOYEE', 'Працівник'), max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
