# Generated by Django 4.2.2 on 2023-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Пошта'),
        ),
    ]
