# Generated by Django 4.2.2 on 2023-12-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='По батькові'),
        ),
    ]
