# Generated by Django 4.2.2 on 2024-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_created_at_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Працівник'), ('DRIVER', 'Водій'), ('TRUCK DRIVER', 'Далекобійник'), ('ENGINEER', 'Інженер'), ('MANAGER', 'Менеджер'), ('COUNTER', 'Бухгалтер'), ('DIRECTOR', 'Директор')], default='EMPLOYEE', max_length=15, verbose_name='Роль'),
        ),
    ]
