# Generated by Django 4.2.2 on 2023-10-18 10:50

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(help_text='(м)', verbose_name='Довжина')),
                ('width', models.PositiveIntegerField(help_text='(мм)', verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(help_text='(мм)', verbose_name='Висота')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='(шт.)', verbose_name='К-ість')),
                ('volume', models.FloatField(help_text='(м³)', verbose_name="Об'єм")),
            ],
            options={
                'verbose_name_plural': 'Raw Materials',
                'ordering': ['length', 'width', 'height', 'quantity', 'volume'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ПІБ клієнта або організація')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBusinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CAR', 'Легкова'), ('TRUCK', 'Фура'), ('SPECIAL', 'Спецтехніка'), ('AGRICULTURAL', 'Сільгосптехніка')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва рами')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('quantity_of_blocks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=300, verbose_name='Вантажовідправник')),
                ('series', models.CharField(max_length=50, verbose_name='Серія ЮІГ')),
                ('delivery_date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('loading_point', models.CharField(max_length=100, verbose_name='Пункт завантаження')),
                ('quantity', models.IntegerField(help_text='шт. в партії', verbose_name='Кількість дерева')),
                ('volume', models.FloatField(help_text='(м³)', verbose_name="Об'єм по ТТН")),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='(грн)', max_digits=10, verbose_name='Загальна сума')),
                ('not_declared', models.BooleanField(default=False, verbose_name='Не декларувати')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Фото квитанції')),
            ],
            options={
                'ordering': ['-created', 'volume', 'total_amount'],
            },
        ),
        migrations.CreateModel(
            name='Sawdust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('DIRECTOR', 'Директор'), ('ENGINEER', 'Інженер'), ('MANAGER', 'Менеджер'), ('COUNTER', 'Бухгалтер'), ('EMPLOYEE', 'Працівник')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='staff_set', related_query_name='staff', to='auth.group', verbose_name='Групи')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='staff_set', related_query_name='staff', to='auth.permission', verbose_name='Права доступу')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WoodChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип дерева')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='Години')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ставка')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата створення/оновлення')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SawCRM.staff', verbose_name='Працівник')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('is_cut', models.BooleanField(default=False, verbose_name='Порізаний')),
                ('length', models.FloatField(help_text='(м). Від 4 до 7', validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Довжина')),
                ('diameter', models.FloatField(help_text='(см)', verbose_name='Діаметр')),
                ('volume', models.FloatField(blank=True, help_text='(м3) Пропустіть, щоб використати константи', null=True, verbose_name="Об'єм")),
                ('batch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SawCRM.rawmaterialbatch', verbose_name='Партія')),
                ('wood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SawCRM.woodtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Raw Materials',
                'ordering': ['length', 'diameter', 'volume', 'wood_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Неактивне'), ('in_progress', 'В процесі'), ('ready', 'Готове до відправки'), ('closed', 'Закрите')], max_length=20, verbose_name='Статус')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Дата відправки')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна замовлення')),
                ('boards', models.ManyToManyField(to='SawCRM.board', verbose_name='Дошка')),
                ('client', models.ManyToManyField(to='SawCRM.clientcontact', verbose_name='Клієнт')),
                ('pallets', models.ManyToManyField(to='SawCRM.pallet', verbose_name='Палети')),
                ('sawdust', models.ManyToManyField(to='SawCRM.sawdust', verbose_name='Тирса')),
                ('woodchip', models.ManyToManyField(to='SawCRM.woodchip', verbose_name='Щепа')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='Дата порізки')),
                ('volume', models.FloatField(blank=True, help_text="(не обов'язково) буде вираховуватись ", null=True, verbose_name="Об'єм")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SawCRM.frame', verbose_name='Рама')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SawCRM.rawmaterial', verbose_name='Сировина')),
            ],
            options={
                'ordering': ['frame', '-created', 'raw_material', 'volume'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='wood_type',
            field=models.ForeignKey(help_text='Тип дерева', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SawCRM.woodtype', verbose_name='Тип дерева'),
        ),
    ]
