# Generated by Django 4.2.2 on 2024-01-02 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SawCRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_date', models.DateField(blank=True, help_text='Дата, коли була виконана перевезення.', null=True, verbose_name='Дата перевезення')),
                ('waybill_number', models.CharField(blank=True, help_text='Номер транспортно-товарної накладної.', max_length=255, null=True, verbose_name='ТТН')),
                ('volume', models.FloatField(blank=True, help_text="Об'єм перевезення.", null=True, verbose_name="Об'єм")),
                ('mileage', models.FloatField(blank=True, help_text='Кількість кілометрів, пройдених транспортом.', null=True, verbose_name='Кілометраж')),
                ('loading_point', models.CharField(blank=True, help_text='Місце, де відбулася завантаження товарів.', max_length=255, null=True, verbose_name='Пункт завантаження')),
                ('delivery_point', models.CharField(blank=True, help_text='Місце, куди була доставлена вантажівка.', max_length=255, null=True, verbose_name='Пункт доставки')),
                ('note', models.TextField(blank=True, help_text='Додаткова інформація чи коментарі.', null=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата і час створення запису.', verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата і час останнього оновлення запису.', verbose_name='Дата оновлення')),
                ('driver', models.ForeignKey(blank=True, help_text='Водій, який виконав роботу.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водій')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkCompletionCertificate',
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='length',
            field=models.FloatField(help_text='(м). Від 4 до 7', verbose_name='Довжина'),
        ),
    ]
