# Generated by Django 4.2.2 on 2024-01-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SawCRM', '0002_completedact_delete_workcompletioncertificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedact',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='completedact',
            name='mileage',
        ),
        migrations.AddField(
            model_name='completedact',
            name='distance',
            field=models.FloatField(blank=True, help_text='Кількість кілометрів, пройдених транспортом.', null=True, verbose_name='Дистація'),
        ),
    ]
