# Generated by Django 4.2.2 on 2024-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SawCRM', '0003_remove_completedact_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedact',
            name='delivery_point',
            field=models.CharField(blank=True, help_text='Місце, куди було доставлено вантаж.', max_length=255, null=True, verbose_name='Пункт доставки'),
        ),
        migrations.AlterField(
            model_name='completedact',
            name='loading_point',
            field=models.CharField(blank=True, help_text='Місце, де відбулося завантаження товарів.', max_length=255, null=True, verbose_name='Пункт завантаження'),
        ),
        migrations.AlterField(
            model_name='completedact',
            name='transport_date',
            field=models.DateField(blank=True, help_text='Дата, коли була виконано перевезення.', null=True, verbose_name='Дата перевезення'),
        ),
    ]
