# Generated by Django 4.2.2 on 2024-01-03 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SawCRM', '0005_alter_completedact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedact',
            options={'ordering': ['-transport_date', 'loading_point', 'delivery_point', '-created_at', 'driver'], 'verbose_name': 'Completed Act', 'verbose_name_plural': 'Completed Acts'},
        ),
        migrations.AddField(
            model_name='completedact',
            name='driver',
            field=models.ForeignKey(help_text='Водій, який виконав роботу.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водій'),
        ),
    ]
